server:
  port: 8686

# database setting
spring:

  # mail setting
  mail:
    host: smtp.naver.com
    port: 465
    username: hodolin24@naver.com
    password: junglim00!
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
    default-encoding: UTF-8
    debug: true

  datasource:
    url: jdbc:mariadb://localhost:3306/jpastudy
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    # DBMS dialect setting
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      # ddl ??? ??? ????...
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # SQL ?? ??? ??? ??
    database: mysql

# log level setting
logging:
  level:
    root: info
    com.study.event.api: debug
    org.hibernate.SQL: debug

# email setting
study:
  mail:
    host: hyelin1124@naver.com